bitvilblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    "posts": PostSitemap,
}
urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

blog/urls.py
from django.urls import path
from blog import views
from .feeds import LatestPostsFeed

app_name = "blog"


urlpatterns = [
    # post views
    path("", views.post_list, name="post_list"),
    path("feeds/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
    path("posts/tags/<slug:tag_slug>/", views.all_post_by_tag, name="post_list_by_tag"),
    path(
        "<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    path(
        "share/<slug:post_slug>/",
        views.post_share,
        name="post_share",
    ),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from taggit.managers import TaggableManager
from blog.managers import CommentManager, PublishedManager
from blog.utils import get_random_string
from django.db.models.signals import pre_save
from django.db import transaction


class Post(models.Model):
    """Post Model"""

    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published"),
    )
    title = models.CharField(_("Blog title"), max_length=250)
    slug = models.SlugField(_("Post slug"), max_length=250,unique=True,blank=True,null=False)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField(_("Blog body"))
    status = models.CharField(
        _("Blog status"), max_length=20, choices=STATUS_CHOICES, default="draft"
    )
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()  # default manager
    published = PublishedManager()  # custom manager for published posts
    tags = TaggableManager()  # tag manager

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        "returns canonical url for each posts"
        return reverse(
            "blog:post_detail",
            args=[
                self.slug,
            ],
        )


@transaction.atomic()
def create_slug(instance, new_slug=None):
    """
    Create and validate slug duplication
    """
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    else:
        qs = Post.objects.filter(slug=slug).order_by("-id")
        exist = qs.exists()
        if exist:
            generated_string = get_random_string(4)
            slug = slug + "-" + generated_string
    return slug


def pre_save_post_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_reciever, sender=Post)


class Comment(models.Model):
    """Comment model"""

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    objects = models.Manager
    commentmanager = CommentManager()

    class Meta:
        ordering = ("-created",)
        db_table = "Comments"

    def __str__(self):
        return f"Comment by {self.email} on {self.post.title}"

blog/forms.py
from django import forms
from blog.models import Comment


class PostSendMailForm(forms.Form):
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("email", "body")

    def save(self, post, *args, **kwargs):

        super(CommentForm, self).save(*args, **kwargs)
        self.post = post
        return self.instance
class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage
from django.views.generic import ListView
from django.db.models import Count
from taggit.models import Tag
from blog.forms import PostSendMailForm, CommentForm, SearchForm
from blog.models import Post, Comment
from blog.utils import post_share_mail
from django.db import transaction
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = "posts"
#     paginate_by = 3
#     template_name = "blog/post/post_list.html"


def all_post_by_tag(request, tag_slug=None):
    all_posts = Post.published.all()
    tag = get_object_or_404(Tag, slug=tag_slug)
    all_tagged_posts = all_posts.filter(tags__in=[tag])
    paginator = Paginator(all_tagged_posts, 3)
    page = request.GET.get("page")  # get the 'page' parameter from the url
    try:
        posts = paginator.page(page)  # get the particular posts for that page
    except PageNotAnInteger:
        posts = paginator.page(
            1
        )  # return the first page if the 'page' value dosent exist
    except EmptyPage:
        posts = paginator.page(
            paginator.num_pages
        )  # returns the last page if the 'page' value is out of range
    context = {"posts": posts, "page": page, "tag": tag}
    return render(request, "blog/post/post_list.html", context)


def post_list(request, tag_slug=None):
    """returns all posts that are published"""
    all_posts = Post.published.all()  # gets all published posts
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        all_posts = all_posts.filter(tags__in=[tag])
    paginator = Paginator(all_posts, 3)  # paginate the posts
    page = request.GET.get("page")  # get the 'page' parameter from the url
    try:
        posts = paginator.page(page)  # get the particular posts for that page
    except PageNotAnInteger:
        posts = paginator.page(
            1
        )  # return the first page if the 'page' value dosent exist
    except EmptyPage:
        posts = paginator.page(
            paginator.num_pages
        )  # returns the last page if the 'page' value is out of range
    context = {"posts": posts, "page": page, "tag": tag}
    return render(request, "blog/post/post_list.html", context)


def post_detail(request, post):
    "returns a single post that is published"
    post = get_object_or_404(
        Post, slug=post, status="published"
    )  # get particular object
    new_comment = None
    comments = post.comments.filter(active=True)  # get all active comments
    if request.method == "POST":
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        Comment.commentmanager.save_comment(comment_form, post)  # save comment

    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:4]
    context = {
        "comments": comments,
        "post": post,
        "comment_form": comment_form,
        "new_comment": new_comment,
        "similar_posts": similar_posts,
    }
    return render(request, "blog/post/post_detail.html", context)


@transaction.atomic()
def post_share(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug, status="published")
    sent = False
    if request.method == "POST":
        form = PostSendMailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_share_mail(request, post, cd)
            sent = True
    else:
        form = PostSendMailForm()
    context = {"form": form, "post": post, "sent": sent}
    return render(request, "blog/post/share.html", context)


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            search_vector = (
                SearchVector("title", weight="A")
                + SearchVector("body", weight="B")
                + SearchVector("tags", weight="B")
            )
            search_query = SearchQuery(query)
            results = (
                Post.published.annotate(
                    search=search_vector, rank=SearchRank(search_vector, search_query)
                )
                .filter(rank__gte=0.3)
                .order_by("-rank")
            )
    return render(
        request,
        "blog/post/search.html",
        {"form": form, "query": query, "results": results},
    )

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
   </ul>

blog/templates/blog/post/post_detail.html

{% extends "blog/base.html" %}{% load blog_tags %} {% block title %}{{ post.title }}{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">Published {{ post.publish }} by {{ post.author }}</p>
{{ post.body|markdown }} {% with comments.count as total_comments %}
<h3>{{ total_comments }} comment{{ total_comments|pluralize }}</h3>
{% endwith %} 
<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}

{% for comment in comments %}
<div class="comment">
  <p class="info">
    Comment {{ forloop.counter }} by {{ comment.email }} {{ comment.created }}
  </p>
  {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are no comments yet.</p>
{% endfor %} 
{% if new_comment %}
<h2>Your comment has been added.</h2>
{% else %}
<h2>Add a new comment</h2>
<form method="post">
  {{ comment_form.as_p }} {% csrf_token %}
  <p><input type="submit" value="Add comment" /></p>
</form>
{% endif %}
<br>
<p>
  <a href="{% url "blog:post_share" post.slug %}">
  Share this post
  </a>
</p>
{% endblock %}

blog/templates/blog/post/post_list.html

 {% extends "blog/base.html" %}{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
<h1>My Blog</h1>
{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
{% for post in posts %}
<h2>
<a href="{{ post.get_absolute_url }}">
{{ post.title }}
</a>

</h2>
<p class="tags">
    Tags:
    {% for tag in post.tags.all %}
    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
    {{ tag.name }}
    </a>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
    </p>
<p class="date">
Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown|truncatewords_html:30}}
<p>
    <a href="{% url "blog:post_share" post.slug %}">
    Share this post
    </a>
</p>
{% endfor %}
{% include "blog/partials/pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}
 {% if query %}
 <h1>Posts containing "{{ query }}"</h1>
 <h3>
 {% with results.count as total_results %}
 Found {{ total_results }} result{{ total_results|pluralize }}
 {% endwith %}
 </h3>
 {% for post in results %}
 <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></
h4>
 {{ post.body|markdown|truncatewords_html:5 }}
 {% empty %}
 <p>There are no results for your query.</p>
 {% endfor %}
 <p><a href="{% url "blog:post_search" %}">Search again</a></p>
 {% else %}
 <h1>Search for posts</h1>
 <form method="get">
 {{ form.as_p }}
 <input type="submit" value="Search">
 </form>
 {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form method="post">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}